{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN48Bm/DkyByXfiBK7feewo"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "\n",
        "# Título de la aplicación\n",
        "st.title(\"Covah - Calculadora de Medidas\")\n",
        "\n",
        "# Funciones de cálculo\n",
        "def calcular_gabinetes_superiores(ancho, alto, tiene_objeto_arriba, tiene_objeto_abajo, num_puertas):\n",
        "    if tiene_objeto_arriba and tiene_objeto_abajo:\n",
        "        alto -= 6  # Restar 6 mm si hay objetos arriba y abajo\n",
        "    elif tiene_objeto_arriba or tiene_objeto_abajo:\n",
        "        alto -= 3  # Restar 3 mm si hay objeto arriba o abajo\n",
        "\n",
        "    if num_puertas == 1:\n",
        "        ancho_puerta = ancho - 4  # Restar 4 mm si es 1 puerta\n",
        "    elif num_puertas == 2:\n",
        "        ancho_puerta = (ancho / 2) - 3  # Dividir y restar 3 mm si son 2 puertas\n",
        "    else:\n",
        "        raise ValueError(\"Número de puertas no válido. Debe ser 1 o 2.\")\n",
        "\n",
        "    return ancho_puerta, alto\n",
        "\n",
        "\n",
        "def calcular_esquinero_superior(ancho, alto, tiene_objeto_arriba, tiene_objeto_abajo):\n",
        "    if tiene_objeto_arriba and tiene_objeto_abajo:\n",
        "        alto -= 6  # Restar 6 mm si hay objetos arriba y abajo\n",
        "    elif tiene_objeto_arriba or tiene_objeto_abajo:\n",
        "        alto -= 3  # Restar 3 mm si hay objeto arriba o abajo\n",
        "\n",
        "    puerta1 = ancho - 28.5 - 1.5 - 0.3\n",
        "    puerta2 = ancho - 28.5 - 0.3\n",
        "\n",
        "    return puerta1, puerta2, alto\n",
        "\n",
        "\n",
        "def calcular_esquinero_inferior(ancho, alto, tiene_objeto_arriba, tiene_objeto_abajo):\n",
        "    if tiene_objeto_arriba and tiene_objeto_abajo:\n",
        "        alto -= 6  # Restar 6 mm si hay objetos arriba y abajo\n",
        "    elif tiene_objeto_arriba or tiene_objeto_abajo:\n",
        "        alto -= 3  # Restar 3 mm si hay objeto arriba o abajo\n",
        "\n",
        "    puerta1 = ancho - 58.5 - 1.5 - 0.3\n",
        "    puerta2 = ancho - 58.5 - 0.3\n",
        "\n",
        "    return puerta1, puerta2, alto\n",
        "\n",
        "\n",
        "def calcular_muebles_inferiores(ancho, num_puertas):\n",
        "    alto_puerta = 67  # El alto de las puertas siempre es 67 cm\n",
        "\n",
        "    if num_puertas == 1:\n",
        "        ancho_puerta = ancho - 3  # Restar 3 mm si es 1 puerta\n",
        "    elif num_puertas == 2:\n",
        "        ancho_puerta = (ancho / 2) - 0.3  # Dividir y restar 0.3 mm si son 2 puertas\n",
        "    else:\n",
        "        raise ValueError(\"Número de puertas no válido. Debe ser 1 o 2.\")\n",
        "\n",
        "    return ancho_puerta, alto_puerta\n",
        "\n",
        "\n",
        "# Gabinetes Superiores\n",
        "st.header(\"Gabinetes Superiores\")\n",
        "ancho_sup = st.number_input(\"Ancho (cm):\", key=\"ancho_sup\")\n",
        "alto_sup = st.number_input(\"Alto (cm):\", key=\"alto_sup\")\n",
        "num_puertas_sup = st.radio(\"Número de puertas:\", [1, 2], key=\"num_puertas_sup\")\n",
        "tiene_objeto_arriba_sup = st.checkbox(\"¿Tiene objeto arriba?\", key=\"objeto_arriba_sup\")\n",
        "tiene_objeto_abajo_sup = st.checkbox(\"¿Tiene objeto abajo?\", key=\"objeto_abajo_sup\")\n",
        "\n",
        "if st.button(\"Calcular Gabinetes Superiores\"):\n",
        "    ancho_puerta_sup, alto_puerta_sup = calcular_gabinetes_superiores(\n",
        "        ancho_sup, alto_sup, tiene_objeto_arriba_sup, tiene_objeto_abajo_sup, num_puertas_sup\n",
        "    )\n",
        "    st.success(f\"Medidas de la puerta: Ancho = {ancho_puerta_sup} cm, Alto = {alto_puerta_sup} cm\")\n",
        "\n",
        "# Gabinetes Inferiores\n",
        "st.header(\"Gabinetes Inferiores\")\n",
        "ancho_inf = st.number_input(\"Ancho (cm):\", key=\"ancho_inf\")\n",
        "alto_inf = st.number_input(\"Alto (cm):\", key=\"alto_inf\")\n",
        "num_puertas_inf = st.radio(\"Número de puertas:\", [1, 2], key=\"num_puertas_inf\")\n",
        "\n",
        "if st.button(\"Calcular Gabinetes Inferiores\"):\n",
        "    ancho_puerta_inf, alto_puerta_inf = calcular_muebles_inferiores(ancho_inf, num_puertas_inf)\n",
        "    st.success(f\"Medidas de la puerta: Ancho = {ancho_puerta_inf} cm, Alto = {alto_puerta_inf} cm\")\n",
        "\n",
        "# Esquinero Superior\n",
        "st.header(\"Esquinero Superior\")\n",
        "ancho_esq_sup = st.number_input(\"Ancho (cm):\", key=\"ancho_esq_sup\")\n",
        "alto_esq_sup = st.number_input(\"Alto (cm):\", key=\"alto_esq_sup\")\n",
        "tiene_objeto_arriba_esq_sup = st.checkbox(\"¿Tiene objeto arriba?\", key=\"objeto_arriba_esq_sup\")\n",
        "tiene_objeto_abajo_esq_sup = st.checkbox(\"¿Tiene objeto abajo?\", key=\"objeto_abajo_esq_sup\")\n",
        "\n",
        "if st.button(\"Calcular Esquinero Superior\"):\n",
        "    puerta1_sup, puerta2_sup, alto_esq_sup = calcular_esquinero_superior(\n",
        "        ancho_esq_sup, alto_esq_sup, tiene_objeto_arriba_esq_sup, tiene_objeto_abajo_esq_sup\n",
        "    )\n",
        "    st.success(f\"Puerta 1: {puerta1_sup} cm, Puerta 2: {puerta2_sup} cm, Alto: {alto_esq_sup} cm\")\n",
        "\n",
        "# Esquinero Inferior\n",
        "st.header(\"Esquinero Inferior\")\n",
        "ancho_esq_inf = st.number_input(\"Ancho (cm):\", key=\"ancho_esq_inf\")\n",
        "alto_esq_inf = st.number_input(\"Alto (cm):\", key=\"alto_esq_inf\")\n",
        "tiene_objeto_arriba_esq_inf = st.checkbox(\"¿Tiene objeto arriba?\", key=\"objeto_arriba_esq_inf\")\n",
        "tiene_objeto_abajo_esq_inf = st.checkbox(\"¿Tiene objeto abajo?\", key=\"objeto_abajo_esq_inf\")\n",
        "\n",
        "if st.button(\"Calcular Esquinero Inferior\"):\n",
        "    puerta1_inf, puerta2_inf, alto_esq_inf = calcular_esquinero_inferior(\n",
        "        ancho_esq_inf, alto_esq_inf, tiene_objeto_arriba_esq_inf, tiene_objeto_abajo_esq_inf\n",
        "    )\n",
        "    st.success(f\"Puerta 1: {puerta1_inf} cm, Puerta 2: {puerta2_inf} cm, Alto: {alto_esq_inf} cm\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cZMoz9rfXP_c",
        "outputId": "0c48f21a-f741-4b5d-95b1-b16c91424bc2"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-01-30 22:38:46.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.521 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.530 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.533 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.548 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.558 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.565 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.571 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.634 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.637 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.659 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.660 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.666 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-01-30 22:38:46.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    }
  ]
}